name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # Puedes cambiar esto por la rama que prefieras (ej. master, develop)
      - dev   # Añadimos la rama dev
  pull_request:
    branches:
      - main
      - dev   # Añadimos la rama dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  # Usamos el token de GitHub predefinido

    - name: Build and push Docker image
      run: |
        if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
          # Construir la imagen de Docker con etiqueta dev
          docker build -t ghcr.io/${{ github.repository_owner }}/acexy-orchestrator:dev .
          docker push ghcr.io/${{ github.repository_owner }}/acexy-orchestrator:dev
        else
          # Construir la imagen de Docker con etiqueta latest (main)
          docker build -t ghcr.io/${{ github.repository_owner }}/acexy-orchestrator:latest .
          docker push ghcr.io/${{ github.repository_owner }}/acexy-orchestrator:latest
        fi
